# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a43f8df9ac60198726c721c18d1e55ed16a3ebc1f786a1b6fbded9edf3e833c328ded10b6e34b32be426e75a35c42f598d74b96a63eff7bc7a713e3d33890fe5

test:
  secret_key_base: ca46c4d18a0117593eb9a08a46415cc24ea1897fded8e82aa8eca59a17bd0f04cf5b52c172b11d0e78bc5e561717855b235f19b97be6d52f2895ab80a7971d18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
